version: '3'
services:
  commerce:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

#version: "3.7"
#
#services:
#  commerce:
#    image: zin354/commerce-chat:latest
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./conf/nginx:/etc/nginx/conf.d
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    ports:
#      - "80:80"
#      - "443:443"
#    #아래 명령어는 ssl인증 이후 적용해야 합니다. 자동갱신 명령입니다.
#    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#  certbot:
#    depends_on:
#      - nginx
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    #아래 명령어는 ssl인증 이후 적용해야 합니다. 자동갱신 명령입니다.
#    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"